<?php

namespace Patnos\SepetBundle\Repository;

/**
 * FirmaTipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FirmaTipRepository extends \Doctrine\ORM\EntityRepository
{
}
