<?php

namespace Patnos\SepetBundle\Repository;

/**
 * SiparisUrunRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiparisUrunRepository extends \Doctrine\ORM\EntityRepository
{
}
