<?php

namespace Patnos\SepetBundle\Repository;

/**
 * SiparisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiparisRepository extends \Doctrine\ORM\EntityRepository
{
}
