<?php

namespace Patnos\SepetBundle\Repository;

/**
 * UrunResimRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UrunResimRepository extends \Doctrine\ORM\EntityRepository
{
}
