<?php

namespace Patnos\SepetBundle\Repository;

/**
 * UrunRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UrunRepository extends \Doctrine\ORM\EntityRepository
{
}
